### PR TITLE
check the length before inserting data into VARCHAR or VARBINARY columns

### LINKED ISSUE #636: DBMS does not enforce VARCHAR length
maxlen specified in varchar(maxlen) seems not work:

```
postgres=# *create* table T(a varchar(3));

>create table T(a varchar(3)) 0

postgres=# *insert* into T values ('abcdefg');

>insert into T values ('abcdefg') 1

postgres=# *select* * from T;

>   a
>---------
>abcdefg
>(1 row)
```

### PR DESCRIPTION
**Pull request by lixupeng**
fix the bug #636. I add a check in planner phase. When generating a InsertPlan,  one should call tuple->SetValue for each element to be inserted. So I add the check in Tuple::SetValue.

### CODE REVIEW

File: src/storage/tuple.cpp [hunk 1]
```diff
@@ -59,6 +59,10 @@ void Tuple::SetValue(const oid_t column_offset, const type::Value &value,
 
   // Skip casting if type is same
   if (type == value.GetTypeId()) {
+    if ((type == type::Type::VARCHAR || type == type::Type::VARBINARY)
+        && value.GetLength() > column_length) {
+      throw peloton::IncompatibleTypeException(type, " data is too long");
```
Comment (apavlo) [inline src/storage/tuple.cpp]: I don't think we want to throw `IncompatibleTypeException` here. Is there another exception type we can throw instead? What does Postgres do?

Comment (lixupeng) [inline src/storage/tuple.cpp]: Postgres reports an ERRCODE_STRING_DATA_RIGHT_TRUNCATION in such situation. Should we add a new Exception for this? 
Is ValueOutOfRangeException or CastException more suitable here?
