### PR TITLE
Fix issue semi-colon bug.

### LINKED ISSUE #681: Remove Semi-Colon Hack
This issue supplants #422.

We currently cannot support queries that have a semi-colon in them. The reason is because the `PacketManager::ExecQueryMessage` splits every incoming query by semi-colons:

https://github.com/cmu-db/peloton/blob/master/src/wire/packet_manager.cpp#L302

This was originally meant to support queries with multiple statements in them:

```sql
SELECT 1; SELECT 2;
```

But this will cause problems if there is a semi-colon **in** the query itself:

```sql
SELECT * FROM foo WHERE col = 'hello;world';
```

-----------------------

We need to refactor the `PacketManager` and `TrafficCop` to be able to handle multi-statement queries. The key thing is that the new SQL parser will return multiple parse trees if there are multiple statements. So we don't need to parse semi-colons manually anywhere in our own code.

Here is a rough outline of what I think we need to do:

1. The first thing to change is obviously to remove the split in `PacketManager::ExecQueryMessage()`. 

   https://github.com/cmu-db/peloton/blob/master/src/wire/packet_manager.cpp#L302

   Then remove the **for** loop in this function. It should not be iterating over multiple queries because it does not know that there are multiple queries.

   https://github.com/cmu-db/peloton/blob/master/src/wire/packet_manager.cpp#L316

2. Refactor `TrafficCop::ExecuteStatement()` to return back an **std::vector** of query results. This is instead of passing the output result buffers by reference as function arguments. Combine the following four items into a object (you can use a name like `StatementResult`):

   https://github.com/cmu-db/peloton/blob/master/src/wire/packet_manager.cpp#L319

   You'll also want to add the `ResultType` status code that `TrafficCop::ExecuteStatement()` currently returns as the function result into the `StatementResult` object.

3. Here's where things get tricky. `TrafficCop::ExecuteStatement()` calls `TrafficCop::PrepareStatement()`.

   https://github.com/cmu-db/peloton/blob/master/src/tcop/tcop.cpp#L149

   This function is where the `TrafficCop` passes the query to the SQL parser:

   https://github.com/cmu-db/peloton/blob/master/src/tcop/tcop.cpp#L286

   I don't know what happens here if there are multiple statements in the query (@haojin2?). The **for** loop at the URL below looks like we can handle it right now:

   https://github.com/cmu-db/peloton/blob/master/src/tcop/tcop.cpp#L299

   But I don't know why there could be multiple statements but then it looks like we are still assuming in the rest of the code that there is only one. So this means that we are going to need to change `TrafficCop::PrepareStatement()` to return multiple `Statement` objects instead of just one.

   Hopefully these changes are localized and we don't have to make major changes in other parts of the code.

### PR DESCRIPTION
**Pull request by ChTimTsubasa**
Fix #681 by deleting the split-query statement and for loop, since the query has already been parsed and split by PostgreSQL client.

### CODE REVIEW

**Comment by ChTimTsubasa** [comment]
A unit test failure occurred in 13-optimizer_sql_test in travis-ci. Specifically: 
13: [0;31m[  FAILED  ] [mOptimizerSQLTests.SelectOrderByTest
13: [0;31m[  FAILED  ] [mOptimizerSQLTests.SelectDistinctTest

I retested it on my own computer but they passed. I have done 
`make check -j4`  
and  
`./test/optimizer_sql_test "--gtest_color=yes" "--gtest_output=xml:./build/test/optimizer_sql_test.xml"`

I also reviewed the failure log in #683 and found has the same failure, while it only changed a line of comment. So is it possible that this of failure is caused by test environment or test code?

**Comment by apavlo** [comment]
@yingjunwu @haoxianghua I think this problem is the same as #655. It's failing in your PR #585

**Comment by PauloAmora** [comment]
Is this reproductible locally?

**Comment by ChTimTsubasa** [comment]
@PauloAmora No, it passed the test locally.

**Comment by PauloAmora** [comment]
I think I found an problem with the tests, unrelated to the PR, will open an issue.

**Comment by seojungmin** [comment]
@ChTimTsubasa @PauloAmora The test fails due to the nondeterministic column ordering with the output of "SELECT *".   AFAIK, since "SELECT *" does not guarantee the order of the column output, and it was supposed to use the column names explicitly instead of *.  This does not fail in a local test, but it does in travis and this is something you could investigate.  For a correct fix, you can refer to the last 2 commits in #682.

**Comment by apavlo** [comment]
@seojungmin Good find. Let's merge your PR in now. This might be the major problem that we needed to overcome before we can merge all the other PRs.

**Comment by yingjunwu** [comment]
Yes I agree with @seojungmin. This is a non-deterministic bug and is independent from the "tuple deletion" bug I am currently working on.

File: src/wire/packet_manager.cpp [hunk 1]
```diff
@@ -294,60 +294,41 @@ bool PacketManager::HardcodedExecuteFilter(std::string query_type) {
...
+    // execute the query using tcop
+    auto status = traffic_cop_->ExecuteStatement(
+        query, result, tuple_descriptor, rows_affected, error_message,
+        thread_id);
+
+    // check status
+    if (status == ResultType::FAILURE) {
+      SendErrorResponse(
+          {{NetworkMessageType::HUMAN_READABLE_ERROR, error_message}});
+    }
```
Comment (seojungmin) [inline src/wire/packet_manager.cpp]: I think we probably need to have `else` here and put the logic for sending the correct response into this `else` block, so that after sending the error response it does not send the result.

Comment (ChTimTsubasa) [inline src/wire/packet_manager.cpp]: I am not the author of this part of the code but your suggestion sounds reasonable. I tested it with `else` on my machine and it passed all test case.

File: src/wire/packet_manager.cpp [hunk 2]
```diff
@@ -294,45 +294,26 @@ bool PacketManager::HardcodedExecuteFilter(std::string query_type) {
 }
 
 // The Simple Query Protocol
+// Fix mis-split bug
```
Comment (apavlo) [inline src/wire/packet_manager.cpp]: Anybody reading the code isn't going to know what you are talking about. Please provide a better description

File: src/wire/packet_manager.cpp [hunk 3]
```diff
@@ -294,45 +294,26 @@ bool PacketManager::HardcodedExecuteFilter(std::string query_type) {
...
-      // check status
-      if (status == ResultType::FAILURE) {
-        SendErrorResponse(
-            {{NetworkMessageType::HUMAN_READABLE_ERROR, error_message}});
-        break;
-      }
-
+  std::string query;
+  PacketGetString(pkt, pkt->len, query);
+  if (!query.empty()) {
```
Comment (apavlo) [inline src/wire/packet_manager.cpp]: Add a comment here that explains when the query could be empty.

File: src/wire/packet_manager.cpp (hunk 2 above)
Comment (ChTimTsubasa) [inline src/wire/packet_manager.cpp]: Added description on this bug

File: src/wire/packet_manager.cpp (hunk 3 above)
Comment (ChTimTsubasa) [inline src/wire/packet_manager.cpp]: Added some pre-process on the query so that it could detect empty query.

**Comment by apavlo** [comment]
@ChTimTsubasa I am going to stop trying fix conflicts directly in Github. Can you rollback c3a58ecb0bdba960615f16bc4a6510c4a808ea3f and then rebase your PR on top of the master?

Sorry about this.

**Comment by ChTimTsubasa** [comment]
No problem. I will do that.
