### PR TITLE
Fix segfault for query on nonexistent tables

### LINKED ISSUE #1055: Segfault when inserting into a nonexistent table
When I write a query like `insert into foo values(33);`, where `foo` is a table not yet created, the client hangs and Peloton server logs show `Segmentation fault: 11`.

### PR DESCRIPTION
**Pull request by schedutron**
Fixes #1055. I had to dig deep into `lldb` for this! I hope I've added the `throw` at the appropriate place. Using throw here also prevents the segfault from happening on, say `update` queries operating on a table that hasn't been created yet.

### CODE REVIEW

**Comment by tcm-marcel** [comment]
Your build fails, fix this first!
https://travis-ci.org/cmu-db/peloton/jobs/328775088#L1405

**Comment by schedutron** [comment]
Oh, sorry! I was missing a semicolon!

**Comment by seojungmin** [comment]
Wouldn't this be a partial solution to the whole problem?  What happens if somebody _delete_ something from a table?

**Comment by schedutron** [comment]
So what should be the appropriate place for checking this? The `select` statements are already validated in `catalog.cpp`, but there's no equivalent for `insert` ones. I think this is the appropriate place to check. I mentioned earlier that this also fixes the problem for `update` queries. And it _does_ work on `delete` queries as well. Quite universal! :)

**Comment by pmenon** [comment]
You need to move this check earlier in processing, ideally during binding. Add the check [here](https://github.com/cmu-db/peloton/blob/master/src/binder/bind_node_visitor.cpp#L177) for `InsertStatement`, similarly to how it's done for `DeleteStatement` [here](https://github.com/cmu-db/peloton/blob/master/src/binder/bind_node_visitor.cpp#L160). The call to `BinderContext:: AddRegularTable()` will throw a CatalogException for you if the table is not in the catalog.

**Comment by schedutron** [comment]
@pmenon Done, and it works as expected!

**Comment by schedutron** [comment]
@pervazea Can you please add back the "ready-for-review" tag?

File: src/optimizer/query_to_operator_transformer.cpp [hunk 1]
```diff
@@ -231,6 +232,10 @@ void QueryToOperatorTransformer::Visit(parser::InsertStatement *op) {
       catalog::Catalog::GetInstance()
           ->GetDatabaseObject(op->GetDatabaseName(), txn_)
           ->GetTableObject(op->GetTableName());
+  
+  if (target_table == nullptr)
```
Comment (pmenon) [inline src/optimizer/query_to_operator_transformer.cpp]: At this point, I don't think `target_table` can be null. Have you found a scenario where the expectation is false?

Comment (schedutron) [reply src/optimizer/query_to_operator_transformer.cpp]: I don't think so. Should I remove this check? Is this code reachable from some other part, apart from a query coming from the postgres front-end?

Comment (schedutron) [reply src/optimizer/query_to_operator_transformer.cpp]: @pmenon  Should I remove this check?

Comment (pmenon) [reply src/optimizer/query_to_operator_transformer.cpp]: @schedutron Yes, it should be safe to remove.

**Comment by pmenon** [comment]
@schedutron You also need to add a unit test.

**Comment by schedutron** [comment]
@pmenon What should be an ideal place for the test? What about [`test/sql/insert_sql_test.cpp`](https://github.com/schedutron/peloton/blob/d69704797aceb3bd014caa9b7b3bc973ebe9276c/test/sql/insert_sql_test.cpp)?

**Comment by pmenon** [comment]
@schedutron Sure, that looks okay.

**Comment by schedutron** [comment]
@pmenon I've added a test.

File: src/optimizer/query_to_operator_transformer.cpp (hunk 1 above)
Comment (pervazea) [reply src/optimizer/query_to_operator_transformer.cpp]: Wasn't this going to be removed?

Comment (schedutron) [reply src/optimizer/query_to_operator_transformer.cpp]: @pervazea Yes, I'll do that in another commit.

**Comment by schedutron** [comment]
@pervazea Done :)

File: test/sql/insert_sql_test.cpp [hunk 2]
```diff
@@ -570,5 +567,34 @@ TEST_F(InsertSQLTests, UniqueColumn) {
...
+          TestingSQLUtil::GeneratePlanWithOptimizer(optimizer, query, txn);
+      EXPECT_EQ(plan->GetPlanNodeType(), PlanNodeType::INSERT);
+      txn_manager.CommitTransaction(txn);
+    } catch (peloton::Exception &ex) {
+      EXPECT_EQ(ExceptionType::CATALOG, ex.GetType());
+      EXPECT_STREQ("Table NotExistTestTable is not found", ex.what());
+      throw peloton::CatalogException(ex.what());
+    }
+  }, peloton::CatalogException);
+  EXPECT_EQ(0, rows_changed);
```
Comment (pmenon) [inline test/sql/insert_sql_test.cpp]: It would make the test clearer if you reduced the scope of the check to where you expect the exception to be thrown. Something like:

```c++
// Setup transaction, optimizer etc. here
std::string query = "...";
EXPECT_THROW(TestingSQLUtil::GeneratePlanWithOptimizer(optimizer, query, txn), 
             peloton::CatalogException);
```

File: src/optimizer/query_to_operator_transformer.cpp [hunk 3]
```diff
@@ -26,6 +26,7 @@
 #include "parser/statements.h"
 
 #include "catalog/manager.h"
+#include "common/exception.h"
```
Comment (pmenon) [inline src/optimizer/query_to_operator_transformer.cpp]: Is this needed?

File: src/include/common/exception.h [hunk 4]
```diff
@@ -129,6 +129,8 @@ class Exception : public std::runtime_error {
     }
   }
 
+  ExceptionType GetType() { return type; }
```
Comment (pmenon) [inline src/include/common/exception.h]: With the changes to your test, do you still need this?

File: src/optimizer/query_to_operator_transformer.cpp (hunk 3 above)
Comment (schedutron) [reply src/optimizer/query_to_operator_transformer.cpp]: We can still catch `CatalogException` without it, so I think it isn't needed. I included it while adding the test just to be safe. I'll remove it.

File: src/include/common/exception.h (hunk 4 above)
Comment (schedutron) [reply src/include/common/exception.h]: Yes, because we need to ensure that the exception of the appropriate type was thrown.

**Comment by schedutron** [comment]
I don't know why the build is failing. The tests fail even for the master branch when I run them locally.

**Comment by tcm-marcel** [comment]
@schedutron we had problems with the build system before, maybe your branch is based on a faulty version. Try to rebase and see if this solves the problem.

**Comment by schedutron** [comment]
Should I rebase with master? The problem is that the build in the master branch is successful, but it makes the Peloton server break when a client connects (see #1141).

**Comment by tcm-marcel** [comment]
I see... I do not know what's the cause of this. Try finding the last working commit in master or simply rebase with the current version, as you currently just need to know, if the build succeeds.

**Comment by pmenon** [comment]
@schedutron It's failing the build because your test is failing. Please make the changes are suggested in my review.

**Comment by schedutron** [comment]
@pmenon I think it's failing because the table name implementation gives lower case table names by default. I Googled this up to check whether SQL table names should be case insensitive and found that DBMSs provide the functionality to enable/disable it. Is there such a provision in Peloton?

The test will pass if I change the expected error message to have the table name in lowercase.

**Comment by schedutron** [comment]
Also, I'd tried earlier to catch `peloton::CatalogException` directly as mentioned in your review, but that hadn't worked. That's why I have to catch the general `peloton::Exception` first and then check its type.

**Comment by schedutron** [comment]
@pmenon The build passed this time.

**Comment by pmenon** [comment]
@schedutron Can you explain why the suggestion of using `EXPECT_THROW` doesn't work? If you're throwing an exception, but you aren't able to catch it is your solution correct?

The test, as it is, is a little brittle - it won't work if we change how we print exceptions.

**Comment by schedutron** [comment]
@pmenon When I was originally writing tests for this, my code was almost identical to what you suggested - `EXPECT_THROW(TestingSQLUtil::GeneratePlanWithOptimizer(optimizer, query, txn), 
             peloton::CatalogException)`, but rather than getting `peloton::CatalogException`, it got `peloton::Exception`. That's why I had to employ the style in my current test.

Why won't the test work if the exception print format changes? Yes, we'll have to change the expected string, but the type of the exception would stay the same, right?

**Comment by schedutron** [comment]
@pmenon But I think I didn't make the test entirely atomic, I'll do that soon, then the test code will be much closer to what you suggested.

**Comment by pmenon** [comment]
@schedutron That probably means we're catching your exception and throwing a different exception rather than re-throwing the original `exception::CatalogException`. Can you dig into where this is happening? I suspect somewhere during optimization.

**Comment by schedutron** [comment]
@pmenon I'll do a debugger session.

**Comment by schedutron** [comment]
@pmenon I'll do a debugger session, but if that's the case, why does `EXPECT_EQ(ExceptionType::CATALOG, ex.GetType())` executes without error?

**Comment by schedutron** [comment]
@pmenon Catching `peloton::CatalogException` works fine, the problem with exception types mentioned above actually occurs in #1063. Sorry for the confusion.

**Comment by schedutron** [comment]
Why did Jenkins fail? The Travis build passed though. @pmenon I think the test is fine now, right?

**Comment by schedutron** [comment]
@pmenon is this PR mergeable now?

File: src/include/common/exception.h (hunk 4 above)
Comment (pmenon) [reply src/include/common/exception.h]: Is this being used anymore? If not remove it.

File: test/sql/insert_sql_test.cpp [hunk 5]
```diff
@@ -570,5 +567,26 @@ TEST_F(InsertSQLTests, UniqueColumn) {
...
+      new optimizer::Optimizer());
+  // Insert an int into a non-existent table.
+  std::string query("INSERT INTO NonExistentTable VALUES(3);");
+  txn = txn_manager.BeginTransaction();
+  EXPECT_THROW({
+    try {
+      TestingSQLUtil::GeneratePlanWithOptimizer(optimizer, query, txn);
+    } catch (peloton::CatalogException &ex) {
+      EXPECT_STREQ("Table nonexistenttable is not found", ex.what());
+      throw peloton::CatalogException(ex.what());
```
Comment (pmenon) [inline test/sql/insert_sql_test.cpp]: Just rethrow here with `throw;`

I'm still not a fan of string equality checks in tests. It creates a tight coupling and because in the long run they'll cause problems if/when we change the string format.

Can you simplify the check here to just fail if you get past the call to `TestingSQLUtil::GeneratePlanWithOptimizer`? You can remove the outer `EXPECT_THROW` .

Comment (schedutron) [reply test/sql/insert_sql_test.cpp]: But if I'll rethrow, the test suite will report that as an error, right? If that's fine, I'll remove the outer `EXCEPT_THROW`. Otherwise, I can just do something like `EXCEPT_THROW(TestingSQLUtil::GeneratePlanWithOptimizer(optimizer, query, txn), peloton::CatalogException);`, just like what you suggested sometime earlier.

**Comment by schedutron** [comment]
@pmenon I've removed the `GetType()` method, now I'll remove the `EXPECT_STREQ`s. Should I also remove you want, the outer `EXPECT_THROW`?

**Comment by schedutron** [comment]
@pmenon Any update on this?

File: test/sql/insert_sql_test.cpp (hunk 5 above)
Comment (pmenon) [reply test/sql/insert_sql_test.cpp]: Remove the outer throw, just fail if you get past the call to `GeneratePlanWithOptimizer()`.

**Comment by schedutron** [comment]
This is perhaps the best thing that happened to me today!
